name: Auto Release Latest Tag
on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  auto-release:
    name: Auto Release Latest Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this action
        id: checkout
        uses: actions/checkout@v4
      - name: Checkout rust_http_proxy
        uses: actions/checkout@v4
        with:
          repository: arloor/rust_http_proxy
          path: rust_http_proxy

      - name: Test this action
        id: test-action
        uses: ./
        with:
          path: rust_http_proxy
          use_musl: false
          extra_deps: cmake zlib1g-dev libelf-dev clang pkg-config make
          after_install: |
            apt-get remove -y gcc
            apt-get install -y gcc-10
            # find / -name libelf.a
            # find / -name libbpf.a
            # find / -name libz.a
            export LIBBPF_SYS_LIBRARY_PATH=/usr/lib:/usr/lib64:/usr/lib/x86_64-linux-gnu
            echo -e "\e[31mLIBBPF_SYS_LIBRARY_PATH=$LIBBPF_SYS_LIBRARY_PATH\e[0m"
          args: -p rust_http_proxy --no-default-features --features aws_lc_rs,bpf_static
          debug: true

      - name: Output
        id: output
        run: |
          echo "release_dir: ${{ steps.test-action.outputs.release_dir }}"
          ls -lh ${{ steps.test-action.outputs.release_dir }}
      - name: Release Latest Tag
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if $(gh release delete latest -y --cleanup-tag); 
            then echo "delete old release"; 
            else echo "no old release";
          fi
          git config --local user.email "admin@arloor.com"
          git config --local user.name "arloor"
          gh release create latest -n "latest" --latest -t latest
